version: '3'

services:
  db:
    image: mongo:3.6.23-xenial
    environment:
      MONGO_INITDB_DATABASE: chatter-db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb-data:/data/db
      - ./config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      default:
      emotives:
        aliases:
          - mongo_db

volumes:
  mongodb-data:

networks:
  emotives:
    external:
      name: emotives
  default:
